### ISSUE TITLE
Panic: The specified procedure could not be found.

### ISSUE THREAD

**Issue by ericdgit** [lxn/win#40]
Hi! Using lxn/win for go-sciter. I get a panic when trying to compile simple examples for go-sciter. I'm on Windows 10, and I use GoLand IDE.

```
panic: The specified procedure could not be found.
goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x7ff9c5670000, 0x4f34c5, 0xe, 0x7ff9c568fef0)
	C:/[mypath]/src/github.com/lxn/win/win.go:57 +0x7d
github.com/lxn/win.init.1()
	C:/[mypath]/src/github.com/lxn/win/comctl32.go:253 +0x191
github.com/lxn/win.init()
	<autogenerated>:1 +0x5e
github.com/sciter-sdk/go-sciter.init()
	<autogenerated>:1 +0x66
main.init()
	<autogenerated>:1 +0x50
```

**Comment by lkarlslund** [comment]
It's fixed in https://github.com/lxn/win/commit/aaf8f59e531a7f484381fbc5453def0cffe9c526, so @lxn you can probably close this issue.

**Comment by lxn** [comment]
Thanks
